# Generated by Django 3.2.19 on 2024-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robrobot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
